%% Generated by the Erlang ASN.1 compiler. Version: 5.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CryptoConditions.

-ifndef(_CRYPTOCONDITIONS_HRL_).
-define(_CRYPTOCONDITIONS_HRL_, true).

-record('SimpleSha256Condition', {
  fingerprint,
  cost
}).

-record('CompoundSha256Condition', {
  fingerprint,
  cost,
  subtypes
}).

-endif. %% _CRYPTOCONDITIONS_HRL_
