%% Generated by the Erlang ASN.1 compiler. Version: 5.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Fingerprints.

-ifndef(_FINGERPRINTS_HRL_).
-define(_FINGERPRINTS_HRL_, true).

-record('PrefixFingerprintContents', {
  prefix,
  maxMessageLength,
  subcondition
}).

-record('ThresholdFingerprintContents', {
  threshold,
  subconditions
}).

-record('RsaFingerprintContents', {
  modulus
}).

-record('Ed25519FingerprintContents', {
  publicKey
}).

-endif. %% _FINGERPRINTS_HRL_
