%% Generated by the Erlang ASN.1 compiler. Version: 5.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Fulfillments.

-ifndef(_FULFILLMENTS_HRL_).
-define(_FULFILLMENTS_HRL_, true).

-record('PreimageFulfillment', {
  preimage
}).

-record('PrefixFulfillment', {
  prefix,
  maxMessageLength,
  subfulfillment
}).

-record('ThresholdFulfillment', {
  subfulfillments,
  subconditions
}).

-record('RsaSha256Fulfillment', {
  modulus,
  signature
}).

-record('Ed25519Sha512Fulfillment', {
  publicKey,
  signature
}).

-endif. %% _FULFILLMENTS_HRL_
