/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptoConditions"
 * 	found in "CryptoConditions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Condition.h"

static asn_oer_constraints_t asn_OER_type_Condition_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Condition_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Condition_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Condition, choice.preimageSha256),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SimpleSha256Condition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"preimageSha256"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Condition, choice.prefixSha256),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompoundSha256Condition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prefixSha256"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Condition, choice.thresholdSha256),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompoundSha256Condition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"thresholdSha256"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Condition, choice.rsaSha256),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SimpleSha256Condition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsaSha256"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Condition, choice.ed25519Sha256),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SimpleSha256Condition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ed25519Sha256"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Condition_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* preimageSha256 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* prefixSha256 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* thresholdSha256 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rsaSha256 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ed25519Sha256 */
};
asn_CHOICE_specifics_t asn_SPC_Condition_specs_1 = {
	sizeof(struct Condition),
	offsetof(struct Condition, _asn_ctx),
	offsetof(struct Condition, present),
	sizeof(((struct Condition *)0)->present),
	asn_MAP_Condition_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Condition = {
	"Condition",
	"Condition",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Condition_constr_1, &asn_PER_type_Condition_constr_1, CHOICE_constraint },
	asn_MBR_Condition_1,
	5,	/* Elements count */
	&asn_SPC_Condition_specs_1	/* Additional specs */
};

