/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Ed25519Sha512Fulfillment.h"

static int
memb_publicKey_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_signature_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_publicKey_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	32	/* (SIZE(32..32)) */};
static asn_per_constraints_t asn_PER_memb_publicKey_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  32,  32 }	/* (SIZE(32..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_signature_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	64	/* (SIZE(64..64)) */};
static asn_per_constraints_t asn_PER_memb_signature_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  64,  64 }	/* (SIZE(64..64)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Ed25519Sha512Fulfillment_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ed25519Sha512Fulfillment, publicKey),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_publicKey_constr_2, &asn_PER_memb_publicKey_constr_2,  memb_publicKey_constraint_1 },
		0, 0, /* No default value */
		"publicKey"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ed25519Sha512Fulfillment, signature),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_signature_constr_3, &asn_PER_memb_signature_constr_3,  memb_signature_constraint_1 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_Ed25519Sha512Fulfillment_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ed25519Sha512Fulfillment_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* publicKey */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* signature */
};
asn_SEQUENCE_specifics_t asn_SPC_Ed25519Sha512Fulfillment_specs_1 = {
	sizeof(struct Ed25519Sha512Fulfillment),
	offsetof(struct Ed25519Sha512Fulfillment, _asn_ctx),
	asn_MAP_Ed25519Sha512Fulfillment_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ed25519Sha512Fulfillment = {
	"Ed25519Sha512Fulfillment",
	"Ed25519Sha512Fulfillment",
	&asn_OP_SEQUENCE,
	asn_DEF_Ed25519Sha512Fulfillment_tags_1,
	sizeof(asn_DEF_Ed25519Sha512Fulfillment_tags_1)
		/sizeof(asn_DEF_Ed25519Sha512Fulfillment_tags_1[0]), /* 1 */
	asn_DEF_Ed25519Sha512Fulfillment_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ed25519Sha512Fulfillment_tags_1)
		/sizeof(asn_DEF_Ed25519Sha512Fulfillment_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ed25519Sha512Fulfillment_1,
	2,	/* Elements count */
	&asn_SPC_Ed25519Sha512Fulfillment_specs_1	/* Additional specs */
};

