/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_PrefixFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_ThresholdFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_RsaFingerprintContents;
extern struct asn_TYPE_descriptor_s asn_DEF_Ed25519FingerprintContents;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Fingerprints in Fingerprints.asn */
	&asn_DEF_PrefixFingerprintContents,	
	&asn_DEF_ThresholdFingerprintContents,	
	&asn_DEF_RsaFingerprintContents,	
	&asn_DEF_Ed25519FingerprintContents,	
	0
};

