/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PrefixFulfillment_H_
#define	_PrefixFulfillment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Fulfillment;

/* PrefixFulfillment */
typedef struct PrefixFulfillment {
	OCTET_STRING_t	 prefix;
	unsigned long	 maxMessageLength;
	struct Fulfillment	*subfulfillment;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrefixFulfillment_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_maxMessageLength_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PrefixFulfillment;
extern asn_SEQUENCE_specifics_t asn_SPC_PrefixFulfillment_specs_1;
extern asn_TYPE_member_t asn_MBR_PrefixFulfillment_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Fulfillment.h"

#endif	/* _PrefixFulfillment_H_ */
#include <asn_internal.h>
