/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PrefixFulfillment.h"

static int
maxMessageLength_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_maxMessageLength_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_maxMessageLength_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_maxMessageLength_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_maxMessageLength_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_maxMessageLength_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_maxMessageLength_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_maxMessageLength_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxMessageLength_3 = {
	"maxMessageLength",
	"maxMessageLength",
	&asn_OP_NativeInteger,
	asn_DEF_maxMessageLength_tags_3,
	sizeof(asn_DEF_maxMessageLength_tags_3)
		/sizeof(asn_DEF_maxMessageLength_tags_3[0]) - 1, /* 1 */
	asn_DEF_maxMessageLength_tags_3,	/* Same as above */
	sizeof(asn_DEF_maxMessageLength_tags_3)
		/sizeof(asn_DEF_maxMessageLength_tags_3[0]), /* 2 */
	{ &asn_OER_type_maxMessageLength_constr_3, &asn_PER_type_maxMessageLength_constr_3, maxMessageLength_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_maxMessageLength_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PrefixFulfillment_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PrefixFulfillment, prefix),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prefix"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrefixFulfillment, maxMessageLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxMessageLength_3,
		0,
		{ &asn_OER_memb_maxMessageLength_constr_3, &asn_PER_memb_maxMessageLength_constr_3,  memb_maxMessageLength_constraint_1 },
		0, 0, /* No default value */
		"maxMessageLength"
		},
	{ ATF_POINTER, 0, offsetof(struct PrefixFulfillment, subfulfillment),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Fulfillment,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subfulfillment"
		},
};
static const ber_tlv_tag_t asn_DEF_PrefixFulfillment_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrefixFulfillment_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* prefix */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxMessageLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* subfulfillment */
};
asn_SEQUENCE_specifics_t asn_SPC_PrefixFulfillment_specs_1 = {
	sizeof(struct PrefixFulfillment),
	offsetof(struct PrefixFulfillment, _asn_ctx),
	asn_MAP_PrefixFulfillment_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PrefixFulfillment = {
	"PrefixFulfillment",
	"PrefixFulfillment",
	&asn_OP_SEQUENCE,
	asn_DEF_PrefixFulfillment_tags_1,
	sizeof(asn_DEF_PrefixFulfillment_tags_1)
		/sizeof(asn_DEF_PrefixFulfillment_tags_1[0]), /* 1 */
	asn_DEF_PrefixFulfillment_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrefixFulfillment_tags_1)
		/sizeof(asn_DEF_PrefixFulfillment_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PrefixFulfillment_1,
	3,	/* Elements count */
	&asn_SPC_PrefixFulfillment_specs_1	/* Additional specs */
};

