/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PreimageFulfillment_H_
#define	_PreimageFulfillment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PreimageFulfillment */
typedef struct PreimageFulfillment {
	OCTET_STRING_t	 preimage;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PreimageFulfillment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PreimageFulfillment;
extern asn_SEQUENCE_specifics_t asn_SPC_PreimageFulfillment_specs_1;
extern asn_TYPE_member_t asn_MBR_PreimageFulfillment_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PreimageFulfillment_H_ */
#include <asn_internal.h>
