/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fingerprints"
 * 	found in "Fingerprints.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RsaFingerprintContents_H_
#define	_RsaFingerprintContents_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RsaFingerprintContents */
typedef struct RsaFingerprintContents {
	OCTET_STRING_t	 modulus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RsaFingerprintContents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RsaFingerprintContents;

#ifdef __cplusplus
}
#endif

#endif	/* _RsaFingerprintContents_H_ */
#include <asn_internal.h>
