/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RsaSha256Fulfillment_H_
#define	_RsaSha256Fulfillment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RsaSha256Fulfillment */
typedef struct RsaSha256Fulfillment {
	OCTET_STRING_t	 modulus;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RsaSha256Fulfillment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RsaSha256Fulfillment;
extern asn_SEQUENCE_specifics_t asn_SPC_RsaSha256Fulfillment_specs_1;
extern asn_TYPE_member_t asn_MBR_RsaSha256Fulfillment_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RsaSha256Fulfillment_H_ */
#include <asn_internal.h>
