/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptoConditions"
 * 	found in "CryptoConditions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SimpleSha256Condition_H_
#define	_SimpleSha256Condition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SimpleSha256Condition */
typedef struct SimpleSha256Condition {
	OCTET_STRING_t	 fingerprint;
	unsigned long	 cost;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleSha256Condition_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cost_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SimpleSha256Condition;
extern asn_SEQUENCE_specifics_t asn_SPC_SimpleSha256Condition_specs_1;
extern asn_TYPE_member_t asn_MBR_SimpleSha256Condition_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleSha256Condition_H_ */
#include <asn_internal.h>
