/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Fulfillments"
 * 	found in "Fulfillments.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ThresholdFulfillment_H_
#define	_ThresholdFulfillment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Fulfillment;
struct Condition;

/* ThresholdFulfillment */
typedef struct ThresholdFulfillment {
	struct ThresholdFulfillment__subfulfillments {
		A_SET_OF(struct Fulfillment) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} subfulfillments;
	struct ThresholdFulfillment__subconditions {
		A_SET_OF(struct Condition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} subconditions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ThresholdFulfillment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThresholdFulfillment;
extern asn_SEQUENCE_specifics_t asn_SPC_ThresholdFulfillment_specs_1;
extern asn_TYPE_member_t asn_MBR_ThresholdFulfillment_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Fulfillment.h"
#include "Condition.h"

#endif	/* _ThresholdFulfillment_H_ */
#include <asn_internal.h>
